# Generated by Django 4.2.3 on 2023-08-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_pledge_supporter_alter_project_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pledge",
            name="comment",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
