# Generated by Django 4.2.3 on 2023-08-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_pledge_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
