# Generated by Django 4.2.3 on 2023-08-05 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_last_modified_alter_project_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="pledge",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pledge",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
