name: Fly Deploy
on:
  push:
    branches:
    # - main

env:
  BRANCH_REF_NAME: ${{ github.ref_name }}

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    name: Deploy app
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}